"use client";
// context
import { alpha, styled } from "@mui/material/styles";
import { HEADER, NAVBAR, SIDEBAR } from "@/src/config";
import Sidebar from "./components/sidebar";

// scroll bar
import "simplebar-react/dist/simplebar.min.css";

// ----------------------------------------------------------------------
const MainStayled = styled("main")(({ theme }) => ({
  backgroundColor: alpha(
    theme.palette.primary.main,
    theme.palette.action.selectedOpacity
  ),
}));
// ----------------------------------------------------------------------

const ContainerStyled = styled("div", {
  shouldForwardProp: (prop) => prop !== "collapseClick",
})(({ theme }) => ({
  [theme.breakpoints.up("lg")]: {
    transition: theme.transitions.create("margin-right", {
      duration: theme.transitions.duration.shorter,
    }),
    marginRight: SIDEBAR.BASE_WIDTH,
  },
}));

// ----------------------------------------------------------------------

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const lgpy = HEADER.DASHBOARD_DESKTOP_HEIGHT + 24;
  return (
    <MainStayled>
      <ContainerStyled>{children}</ContainerStyled>
      <Sidebar />
    </MainStayled>
  );
}
